name: Release and Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    uses: lvjiaxuan/github-action-templates/.github/workflows/lvr-release.yml@main
    secrets: inherit

  publish:
    uses: lvjiaxuan/github-action-templates/.github/workflows/publish.yml@main
    secrets: inherit
